### ISSUE TITLE
Fetch relationship should be able to fetch config relationship

### ISSUE THREAD

**Issue by thabalija** [infinum/ngx-hal#132]
If a model is declared with a property which has `externalName` set to `'config'`:

```
@ModelConfig({
	type: 'MyModel',
})
class MyModel extends HalModel {
    @HasOne({
        externalName: 'config',
    })
    public someName: ...
}
```

then `model.fetchRelationships('someName')` will return `ModelConfig` - `{ type: 'MyModel' }` instead of fetching the real config relationship.

**Comment by safo6m** [comment]
If I understood the issue correctly, when calling `model.fetchRelationships('someName')`, you would expect `SomeNameClass` as a response.

According to [the docs](https://github.com/infinum/ngx-hal/wiki/HalModel#fetchrelationships), `fetchRelationships` always returns an instance of the original model. Therefore, in your case, it is expected of `fetchRelationships` to return an instance of `MyModel`.

The reason for such behaviour is to have consistent responses as the `fetchRelationships` method accepts multiple relationship names.

Your exact case is covered with the unit test - #153

Feel free to open another issue if the original problem is not resolved.
