### ISSUE TITLE
Uncaught error when including non existing relationship

### ISSUE THREAD

**Issue by thabalija** [infinum/ngx-hal#35]
Steps to reproduce:
- create a model with a `@HasMany` relationship (e.g. `'items'`).
- `find` that model with wrong `includeRelationship` as param (e.g. `'item'` instead of `'items'`)

Error:
`Uncaught TypeError: Cannot read property 'externalName' of undefined at getRelationshipUrl.`

**Comment by safo6m** [comment]
This is fixed in version `0.0.62`.
