### ISSUE TITLE
Can't fetch links

### ISSUE THREAD

**Issue by rnorden** [infinum/ngx-hal#66]
This is my model:

```json
      {
        "foo": "foo",
        "bar": "bar",
        "_links": {
          "self": {
            "href": "http://localhost:8080/modelA/1"
          },
          "modelA": {
            "href": "http://localhost:8080/modelA/1"
          },
          "modelB": {
            "href": "http://localhost:8080/modelA/1/modelB"
          }
        }
      },
```

This is my modelA resource:
```typescript
export type Foo= string;
export type Bar= string;

export interface ModelA{
  foo: Foo;
  bar: Bar;
}
```

When I run the following code runs:

```typescript
modelAService.findOne('1').subscribe( (modelA: ModelA) => {
    modelA.fetchRelationships('modelB').subscribe( (modelB: ModelB) => { console.log(modelB); });
});
```

my `modelA` gets logged?
I've followed the code and I think DataStoreService::fetchModelRelationships contains
```javascript
        if (!relationships$.length) {
            return of(model);
        }
```
which just returns modelA because it can't find my `_links.modelB` relation?

**Comment by rnorden** [comment]
Sorry, I've pasted my wrong `modelA` resource. The correct one was:
```typescript
export class ModelAResource extends HalModel implements ModelA {
  @Attribute()
  foo: Foo;
  @Attribute()
  bar: Bar;
}
```

Since then I've added 
```typescript
  @HasMany({ itemsType: ModelBResource, externalName: "modelB" })
  modelB: ModelBResource[];
```

and I get the error
```TypeError: can't redefine non-configurable property "modelB" ```

**Comment by safo6m** [comment]
@rnorden sorry for not getting back to you sooner.
Here is the docs for [fetchRelationships method](https://github.com/infinum/ngx-hal/wiki/HalModel#fetchrelationships)

as you can see, `fetchRelationships` method returns the original model, not the relationship model.

> ```ts
> modelAService.findOne('1').subscribe( (modelA: ModelA) => {
>     modelA.fetchRelationships('modelB').subscribe( (modelB: ModelB) => { console.log(modelB); });
> });
> ```
> 
> my `modelA` gets logged?

...and that's the reason why your `modelA` is being logged out. The correct naming would be:

```ts
modelAService.findOne('1').subscribe( (modelA: ModelA) => {
    modelA.fetchRelationships('modelB').subscribe( (modelA: ModelA) => { console.log(modelA); });
});
```

Note that you can also pass `modelB` relationship name in `findOne` method so you won't need the inner request in that case.

```ts
modelAService.findOne('1', ['modelB']).subscribe( (modelA: ModelA) => {
    console.log(modelA, modelA.modelB);
});
```

Regarding your second issue:

> ```ts
>   @HasMany({ itemsType: ModelBResource, externalName: "modelB" })
>   modelB: ModelBResource[];
> ```
> and I get the error
> TypeError: can't redefine non-configurable property "modelB"

I haven't succeeded to reproduce this issue, can you give me a bit more information?
