### ISSUE TITLE
Cannot Initialise property with @HasOne decorator

### ISSUE THREAD

**Issue by manurajsingh** [infinum/ngx-hal#68]
**Environment**
Angular CLI: 9.0.7
Node: 12.16.0
OS: win32 x64 (Windows 10)
Angular: 9.0.7
Ivy Workspace: Yes
ngx-hal: 1.1.2

**Issue**
@HasOne decorator on a property causes following
ERROR TypeError: Cannot redefine property: address
    at Function.defineProperty (<anonymous>)
    at ngx-hal.js:1131
    at Array.forEach (<anonymous>)
    at User.initializeHasOneProperties (ngx-hal.js:1126)
    at new HalModel (ngx-hal.js:730)
    at new User (User.ts:5)
    at HalDatastoreService.createHalDocument (ngx-hal.js:1828)
    at HalDatastoreService.processRawResource (ngx-hal.js:2344)
    at MapSubscriber.project (ngx-hal.js:2258)
    at MapSubscriber._next (map.js:29)

```
initializeHasOneProperties() {
        this.hasOneProperties.forEach((
        (property) => {
            _Object.defineProperty(HalModel.prototype, property.name,...._
```

**Response From Server-Side**
```
{
	"_embedded": {
		"userList": [
			{
				"id": "18f14cb7-bbcf-4b2c-8c48-2e037a0ca757",
				"hidden": false,
				"forename": "Tom0",
				"surname": "Black0",
				"age": 21,
				"_embedded": {
					"address": {
						"id": "0517796e-4708-4b11-a2b6-f90583b670f1",
						"hidden": false,
						"line1": "First Line Of Address 8",
						"line2": "Second Line Of Address 8",
						"line3": null,
						"postcode": "PO8 8CD"
					}
				},
				"_links": {
					"self": {
						"href": "http://127.0.0.1:8083/users/18f14cb7-bbcf-4b2c-8c48-2e037a0ca757"
					},
					"address": {
						"href": "http://127.0.0.1:8083/addresses/0517796e-4708-4b11-a2b6-f90583b670f1"
					}
				}
			},
			{
				"id": "ba020988-a874-4f35-b376-2568138bd2fe",
				"hidden": false,
				"forename": "Tom1",
				"surname": "Black1",
				"age": 22,
				"_embedded": {
					"address": {
						"id": "0fcd0056-8382-48e4-8d3e-cf587ebd675b",
						"hidden": false,
						"line1": "First Line Of Address 1",
						"line2": "Second Line Of Address 1",
						"line3": null,
						"postcode": "PO1 1CD"
					}
				},
				"_links": {
					"self": {
						"href": "http://127.0.0.1:8083/users/ba020988-a874-4f35-b376-2568138bd2fe"
					},
					"address": {
						"href": "http://127.0.0.1:8083/addresses/0fcd0056-8382-48e4-8d3e-cf587ebd675b"
					}
				}
			}
		]
	},
	"_links": {
		"first": {
			"href": "http://127.0.0.1:8083/users?page=0&size=2"
		},
		"self": {
			"href": "http://127.0.0.1:8083/users?page=0&size=2"
		},
		"next": {
			"href": "http://127.0.0.1:8083/users?page=1&size=2"
		},
		"last": {
			"href": "http://127.0.0.1:8083/users?page=1&size=2"
		}
	},
	"page": {
		"size": 2,
		"totalElements": 4,
		"totalPages": 2,
		"number": 0
	}
}
```

**User Model**
```
@ModelConfig({ type: 'user', endpoint: 'users' })
export class User extends HalModel {
    @Attribute()
    public forename: string;
    @Attribute()
    public surname: string;
    @Attribute()
    public age: number;
    @HasOne({ propertyClass: Address })
    public address: Address;
}
```

**Address Model**
```
@ModelConfig({ type: 'address', endpoint: 'addresses' })
export class Address extends HalModel {
    @Attribute()
    public line1: string;
    @Attribute()
    public line2: string;
    @Attribute()
    public line3: string;
    @Attribute()
    public postcode: string;
}
```

**Call to Get Users (HalDocument) Unable to Initialise Address**
Call to find with fetchRelationships causes above error.
```
this.userService.find({}, true, ['address']).subscribe((res: HalDocument<User>) => {
      console.log(res.models);
    });

```
Note that switching address decorator with @Attribute allows it to work but of course it fails down the line where modelClass for Address cannot be located.

**Comment by manurajsingh** [comment]
Issue above is that supprting dependency does not support AOT that is enabled by default in Angular 9. Hence, 
I have changed following compiler option in tsconfig.json
`"target": "es5",`
I have switched off Ivy in tsconfig.app.json
```
"angularCompilerOptions": {
    "enableIvy": false
  }
```
Also in angular.json
`"aot": false,`

**Comment by manurajsingh** [comment]
Upon doing so, @HasOne decorator was initialised correctly.

Although, I believe, ngx-hal should start supporting Ivy or have library dependencies that support Ivy.

**Comment by safo6m** [comment]
@manurajsingh thank you for reporting the issue, I'll take care of that during the next week.

**Comment by manurajsingh** [comment]
@safo6m thanks. If you require any artifacts, please do let me know.

**Comment by safo6m** [comment]
@manurajsingh I haven't prepared the library for Angular 9/10 yet, but your issue is not related directly to Ivy.
I implemented a temporary solution for your case (follow up issue: #73)

The version [v1.1.3](https://github.com/infinum/ngx-hal/releases/tag/v1.1.3) contains the fix.
Please give a try.

**Comment by manurajsingh** [comment]
@safo6m Thanks for the new release and pur time into updating the codebase.

I have attempted to use v1.1.3 as dependency and it looks like that it working. Other that changing the version, I have updated compilerOptions in tsConfig.ts to be "target": "es2015" instead of "target": "es5" that did not work in v1.1.2. In v1.1.2 using "es5" was the only option to get embedded relationships.

**Comment by manurajsingh** [comment]
All my exist unit tests passed other than the one that I just worte that is failing.  I am calling find on datastoreService with requestOptions where I am assiging 'httpparams' an HTTPParams object. It may be historic issue.

**Comment by manurajsingh** [comment]
@safo6m Here is a unit test for replicating HttpParams issue

```
it('should make a GET request with request body', () => {
            const paramName1 = 'testParam';
            const paramValue1 = 'paramVal';

            const httpParams = new HttpParams().set(paramName1, paramValue1);
            datastoreService.find(DummyModel, {}, true, [], { params: httpParams }).subscribe();

            const req: TestRequest = httpTestingController
                .expectOne(BASE_NETWORK_URL + '/' + 'dummy' + '?' + paramName1 + '=' + paramValue1);
            expect(req.request.method).toEqual('GET');

            req.flush('');
        });
```

Results ->
Expected URL = `http://test:1234/dummy?testParam=paramVal`
Actual URL = `http://test:1234/dummy?updates=%5Bobject%20Object%5D&cloneFrom=%5Bobject%20Object%5D&encoder=%5Bobject%20Object%5D&map=null`

I am guessing that HttpParams are being formed errorneously to build a url.

**Comment by safo6m** [comment]
@manurajsingh I wasn't aware of that issue but as it's not related to the original issue from this thread, I've extracted it into a new one.

I'm closing this one as the original problem is fixed and the discussion regarding `HttpParams` can be continued in #77
