### ISSUE TITLE
Params not parsed correctly when passed as HttpParams

### ISSUE THREAD

**Issue by safo6m** [infinum/ngx-hal#77]
Here is a unit test for replicating HttpParams issue

```
it('should make a GET request with request body', () => {
            const paramName1 = 'testParam';
            const paramValue1 = 'paramVal';

            const httpParams = new HttpParams().set(paramName1, paramValue1);
            datastoreService.find(DummyModel, {}, true, [], { params: httpParams }).subscribe();

            const req: TestRequest = httpTestingController
                .expectOne(BASE_NETWORK_URL + '/' + 'dummy' + '?' + paramName1 + '=' + paramValue1);
            expect(req.request.method).toEqual('GET');

            req.flush('');
        });
```

Results ->
Expected URL = `http://test:1234/dummy?testParam=paramVal`
Actual URL = `http://test:1234/dummy?updates=%5Bobject%20Object%5D&cloneFrom=%5Bobject%20Object%5D&encoder=%5Bobject%20Object%5D&map=null`

I am guessing that HttpParams are being formed errorneously to build a url.

Thanks.

_Originally posted by @manurajsingh in https://github.com/infinum/ngx-hal/issues/68#issuecomment-668629953_

**Comment by manurajsingh** [comment]
@safo6m Excellent.
I thought, it may be side effect of change in v1.1.3, clearly it is historic then.
Thanks for opening new discussion.

**Comment by safo6m** [comment]
@manurajsingh The issue should be fixed in [v1.1.4](https://github.com/infinum/ngx-hal/releases/tag/v1.1.4)

**Comment by manurajsingh** [comment]
@safo6m Thanks for a quick response.
 
I have tested following findOne and request -> Successfully

However, find method on datastore service is still causing same issue. I guess this because of  deepmerge going on for params with request options (line 415) in datastore.service.ts which is pre to makeGetRequest (where the fix is).

Here is the unit test with issue
```
it('should make a GET request with HTTP params', () => {
            const paramName1 = 'testParam';
            const paramValue1 = 'paramVal';

            const httpParams = new HttpParams().set(paramName1, paramValue1);
            datastoreService.find(DummyModel, {}, true, [], { params: httpParams }).subscribe();

            const req: TestRequest = httpTestingController
                .expectOne(BASE_NETWORK_URL + '/' + 'dummy' + '?' + paramName1 + '=' + paramValue1);
            expect(req.request.method).toEqual('GET');

            req.flush('');
        });
```

Thanks.

**Comment by safo6m** [comment]
Thanks for the testing.
According to [the documentation](https://github.com/infinum/ngx-hal/wiki/ModelService#find), `find` method accepts `object` as params, not `HttpParams` 
```js
find(params: object): Observable<Array<Model>>;
```

Nevertheless, there is no reason for not supporting `HttpParams` as well. I've added the support for it and it will be included in the next release. 
For now you can test it with the version [v2.0.3-beta](https://github.com/infinum/ngx-hal/releases/tag/v2.0.3-beta) (I haven't tested it yet)

**Comment by manurajsingh** [comment]
Thanks @safo6m 
The documentation is referring to multiple signatures (one of them is)
`
find(params: object, includeMeta: boolean, includeRelationships: Array<string>, requestOptions: RequestOptions, subsequentRequestsOptions: RequestOptions): Observable<HalDocument<Model>>;
`

As with `findOne` `requestOptions ` has params that are of type `HttpParams`. RequestOptions further offer additional bits such as Headers and observe that are very useful.

I will continue to use v1.1.4 with params for now.

Thanks for looking into the matter. I look forward to the next release. Is there a timeline to it?

**Comment by safo6m** [comment]
There were couple of releases after this discussion. The first release with the changes dicussed here is [v2.0.0](https://github.com/infinum/ngx-hal/releases/tag/2.0.0).
Feel free to create a new issue if something else is missing.
